/* ==========================================================================
   MIND 40 GAME CATALOG DEFINITIONS (EXACTLY 40 GAMES)
   ========================================================================== */

export const GAMES_CATALOG = [
  // --- MEMORY (1-7) ---
  {
    id: 'digit_span_forward',
    name: 'Digit Span Forward',
    category: 'Memory',
    difficulty: 1,
    description: 'Memorize a sequence of numbers and reproduce them in exact order.',
    tutorial: 'Numbers will flash one by one. Enter the sequence in the same forward order.',
  },
  {
    id: 'digit_span_backward',
    name: 'Digit Span Backward',
    category: 'Memory',
    difficulty: 2,
    description: 'Memorize a sequence of numbers and enter them in reverse order.',
    tutorial: 'Pay close attention to the sequence, then enter the digits backwards.',
  },
  {
    id: 'corsi_blocks',
    name: 'Corsi Block Tapping',
    category: 'Memory',
    difficulty: 2,
    description: 'Remember and tap highlighted spatial blocks on a 3D grid in sequence.',
    tutorial: 'Watch blocks light up on the spatial grid, then tap the exact blocks in sequence.',
  },
  {
    id: 'spatial_span',
    name: 'Spatial Span',
    category: 'Memory',
    difficulty: 3,
    description: 'Recall the exact spatial positions of targets on an expanding matrix.',
    tutorial: 'Remember positions where shapes briefly light up on the matrix.',
  },
  {
    id: 'picture_recall',
    name: 'Picture Scene Recall',
    category: 'Memory',
    difficulty: 2,
    description: 'Observe a visual scene for 5 seconds, then answer specific recall details.',
    tutorial: 'Study the generated illustration carefully before answering questions.',
  },
  {
    id: 'face_name_memory',
    name: 'Avatar Name Association',
    category: 'Memory',
    difficulty: 3,
    description: 'Pair fictional avatar portraits with names, then identify correct matches.',
    tutorial: 'Remember avatar faces and their associated names, then pick the matching pair.',
  },
  {
    id: 'visual_pattern_memory',
    name: 'Visual Pattern Memory',
    category: 'Memory',
    difficulty: 4,
    description: 'Memorize shaded matrix tiles and recreate the pattern from memory.',
    tutorial: 'A grid of tiles lights up briefly. Re-shade the exact tiles after they hide.',
  },

  // --- ATTENTION / INHIBITION (8-14) ---
  {
    id: 'stroop_sprint',
    name: 'Stroop Sprint',
    category: 'Attention',
    difficulty: 2,
    description: 'Respond to ink color while inhibiting word text meaning.',
    tutorial: 'Select the color the word is WRITTEN in, ignoring what the word says!',
  },
  {
    id: 'trail_making_a',
    name: 'Trail Making A',
    category: 'Attention',
    difficulty: 1,
    description: 'Connect numbered targets sequentially in ascending order (1-2-3-4).',
    tutorial: 'Tap numbers in ascending order (1 → 2 → 3 → 4) as fast as possible.',
  },
  {
    id: 'trail_making_b',
    name: 'Trail Making B',
    category: 'Attention',
    difficulty: 3,
    description: 'Alternate connecting numbers and letters (1-A-2-B-3-C).',
    tutorial: 'Alternate between numbers and letters in sequence (1 → A → 2 → B → 3 → C).',
  },
  {
    id: 'go_no_go',
    name: 'Go / No-Go Response',
    category: 'Attention',
    difficulty: 2,
    description: 'Tap rapidly on "Go" green stimuli, but strictly withhold on red "No-Go".',
    tutorial: 'Tap quickly when GREEN appears. DO NOT tap when RED appears.',
  },
  {
    id: 'flanker_task',
    name: 'Eriksen Flanker Task',
    category: 'Attention',
    difficulty: 3,
    description: 'Identify the direction of the center arrow while ignoring flanking arrows.',
    tutorial: 'Focus ONLY on the center arrow. Tap LEFT or RIGHT based on its direction.',
  },
  {
    id: 'simon_task',
    name: 'Simon Interference Task',
    category: 'Attention',
    difficulty: 3,
    description: 'Respond to target color regardless of which side of the screen it appears on.',
    tutorial: 'Match color key bindings ignoring whether the target pops up left or right.',
  },
  {
    id: 'multiple_object_tracking',
    name: 'Multiple Object Tracking',
    category: 'Attention',
    difficulty: 4,
    description: 'Track multiple moving target spheres as they bounce among distractors.',
    tutorial: 'Watch the highlighted targets move, then select them after motion stops.',
  },

  // --- EXECUTIVE FUNCTION / PLANNING (15-20) ---
  {
    id: 'wisconsin_card_sorting',
    name: 'Adaptive Rule Sorting',
    category: 'Executive',
    difficulty: 4,
    description: 'Deduce hidden sorting rules (color, shape, count) from feedback and adapt when rules change.',
    tutorial: 'Sort cards under 4 piles. Deduce whether rule is color, shape, or number!',
  },
  {
    id: 'tower_of_hanoi',
    name: 'Tower of Hanoi',
    category: 'Executive',
    difficulty: 4,
    description: 'Move disk stacks to target peg without placing larger disks on smaller ones.',
    tutorial: 'Transfer all disks to the goal peg. Never place a larger disk atop a smaller one.',
  },
  {
    id: 'rule_switching',
    name: 'Rule Switching Challenge',
    category: 'Executive',
    difficulty: 3,
    description: 'Switch between sorting by number parity vs shape color depending on cue.',
    tutorial: 'When cue says NUMBERS, sort odd/even. When cue says SHAPE, sort color.',
  },
  {
    id: 'dual_task',
    name: 'Dual Task Multitasking',
    category: 'Executive',
    difficulty: 5,
    description: 'Perform visual tracking and auditory pitch detection simultaneously.',
    tutorial: 'Keep the ball centered while simultaneously pressing key on high-pitch tones.',
  },
  {
    id: 'category_sorting',
    name: 'Category Semantic Sorting',
    category: 'Executive',
    difficulty: 2,
    description: 'Sort dynamic words into semantic categories under time pressure.',
    tutorial: 'Swipe or tap items to left/right category bins as fast as possible.',
  },
  {
    id: 'maze_planning',
    name: 'Labyrinth Route Planning',
    category: 'Executive',
    difficulty: 3,
    description: 'Plan a complete path through a complex maze before executing moves.',
    tutorial: 'Trace the optimal route from entrance to exit avoiding dead ends.',
  },

  // --- SPEED (21-26) ---
  {
    id: 'simple_reaction',
    name: 'Simple Reaction Time',
    category: 'Speed',
    difficulty: 1,
    description: 'Tap immediately when the screen changes color or stimulus appears.',
    tutorial: 'Wait for the screen to turn GREEN, then tap as fast as you can!',
  },
  {
    id: 'choice_reaction',
    name: 'Choice Reaction Time',
    category: 'Speed',
    difficulty: 2,
    description: 'Tap left or right button depending on target arrow direction.',
    tutorial: 'Tap LEFT for left arrow, RIGHT for right arrow immediately.',
  },
  {
    id: 'rapid_symbol',
    name: 'Rapid Symbol Recognition',
    category: 'Speed',
    difficulty: 2,
    description: 'Match target symbols against a reference key under rapid timer.',
    tutorial: 'Compare target symbol against key pairs and tap matching code number.',
  },
  {
    id: 'number_reaction',
    name: 'Number Parity Reaction',
    category: 'Speed',
    difficulty: 2,
    description: 'React instantly to EVEN vs ODD numbers.',
    tutorial: 'Tap LEFT for Even, RIGHT for Odd as fast as possible.',
  },
  {
    id: 'shape_reaction',
    name: 'Shape Matching Reaction',
    category: 'Speed',
    difficulty: 2,
    description: 'React when two consecutive shapes are identical.',
    tutorial: 'Tap MATCH whenever current shape equals the previous shape!',
  },
  {
    id: 'color_reaction',
    name: 'Color Burst Reaction',
    category: 'Speed',
    difficulty: 1,
    description: 'React to designated target color bursts.',
    tutorial: 'Tap when the target color appears, ignore all other colors.',
  },

  // --- SPATIAL / VISUAL (27-32) ---
  {
    id: 'mental_rotation',
    name: '3D Mental Rotation',
    category: 'Spatial',
    difficulty: 3,
    description: 'Determine if rotated 3D block figures are identical or mirror images.',
    tutorial: 'Rotate shapes in your mind to see if they match the original figure.',
  },
  {
    id: 'block_design',
    name: 'Block Design Reconstruction',
    category: 'Spatial',
    difficulty: 4,
    description: 'Reconstruct target geometric patterns using colored blocks.',
    tutorial: 'Rotate and place blocks to match the goal pattern.',
  },
  {
    id: 'mirror_image',
    name: 'Mirror Image Identification',
    category: 'Spatial',
    difficulty: 3,
    description: 'Identify correct reflected mirror images vs non-matching rotations.',
    tutorial: 'Pick the true mirror reflection of the given target image.',
  },
  {
    id: 'spatial_matching',
    name: 'Spatial Grid Alignment',
    category: 'Spatial',
    difficulty: 3,
    description: 'Match spatial coordinate arrangements across rotated frames.',
    tutorial: 'Align grid dots to match the target reference perspective.',
  },
  {
    id: 'map_navigation',
    name: 'Map Route Navigation',
    category: 'Spatial',
    difficulty: 3,
    description: 'Remember turn sequences on a city map and navigate from memory.',
    tutorial: 'Memorize route turns (Left, Right, Straight) then navigate the intersections.',
  },
  {
    id: 'change_blindness',
    name: 'Change Blindness Scene',
    category: 'Spatial',
    difficulty: 3,
    description: 'Identify subtle differences between alternating visual scenes.',
    tutorial: 'Spot the object that changes between the two flickering images.',
  },

  // --- REASONING (33-38) ---
  {
    id: 'raven_matrix',
    name: 'Matrix Pattern Reasoning',
    category: 'Reasoning',
    difficulty: 4,
    description: 'Identify logical geometric progression rules to fill missing matrix cell.',
    tutorial: 'Analyze row and column patterns to select the missing tile option.',
  },
  {
    id: 'pattern_completion',
    name: 'Visual Pattern Completion',
    category: 'Reasoning',
    difficulty: 3,
    description: 'Select the exact piece that completes a complex geometric design.',
    tutorial: 'Choose the correct fragment to complete the symmetry pattern.',
  },
  {
    id: 'odd_one_out',
    name: 'Odd One Out Deduction',
    category: 'Reasoning',
    difficulty: 2,
    description: 'Find the single object that does not follow the shared rule.',
    tutorial: 'Identify which item breaks the common visual or logical rule.',
  },
  {
    id: 'logic_grid',
    name: 'Logic Grid Puzzle',
    category: 'Reasoning',
    difficulty: 4,
    description: 'Deduce relationships between items from clue constraints.',
    tutorial: 'Use true/false elimination grid clues to match items.',
  },
  {
    id: 'sequence_prediction',
    name: 'Sequence Rule Prediction',
    category: 'Reasoning',
    difficulty: 3,
    description: 'Predict the next number or shape in a rule-based sequence.',
    tutorial: 'Discover the mathematical/logical progression rule and select the next item.',
  },
  {
    id: 'abstract_reasoning',
    name: 'Abstract Rule Solver',
    category: 'Reasoning',
    difficulty: 4,
    description: 'Solve novel abstract visual transformation puzzles.',
    tutorial: 'Determine how shapes transform across steps and apply the rule to the target.',
  },

  // --- MIXED FUSION (39-40) ---
  {
    id: 'hidden_object',
    name: 'Hidden Object Search',
    category: 'Mixed',
    difficulty: 3,
    description: 'Locate designated target items embedded inside dense visual clutter.',
    tutorial: 'Find and tap all hidden items listed on your target board.',
  },
  {
    id: 'challenge_fusion',
    name: 'Challenge Fusion Workout',
    category: 'Mixed',
    difficulty: 5,
    description: 'Adaptive multi-task workout chaining challenges across all dimensions.',
    tutorial: 'Complete a seamlessly chained sequence of memory, speed, and logic tasks.',
  },
];
